[project]
# Used by cx_Freeze
name = "apc-lemmy-bot"
version = "0.1.1"
description = "Post supabase events to a Lemmy instance or show them."

[tool.poetry]
name = "apc-lemmy-bot"
version = "0.1.1"
description = "Post supabase events to a Lemmy instance or show them."
authors = ["Carles Muñoz Gorriz <carlesmu@internautas.org>"]
maintainers = ["Carles Muñoz Gorriz <carlesmu@internautas.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
packages = [{include = "apc_lemmy_bot"}]
keywords = ["lemmy"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
typer = "^0.9.0"
typing-extensions = "^4.6.3"
supabase = "^1.0.3"
pythorhead = "^0.9.2"
sqlalchemy = "^2.0.17"
sqlalchemy-utils = "^0.41.1"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = "^2.17.4"
pre-commit = "^3.3.3"
trove-classifiers = "^2023.5.24"  # for classifiers in this file
commitizen = "^3.5.2"
poetry = "^1.5.1"
prompt-toolkit = "^3.0.38"  # for comitizen 3.5.2
cx-freeze = "^6.15.2"
mypy = "^1.4.1"


[tool.poetry.group.IDE.dependencies]
spyder = {version="^5.4.3", optional = true}
python-lsp-black = {version = "^1.3.0", optional = true}
docstring-to-markdown = {version = "^0.12", optional = true}
jedi = {version = "^0.18.2", optional = true}
parso = {version = "^0.8.3", optional = true}
pluggy = {version = "^1.2.0", optional = true}
python-lsp-jsonrpc = {version = "^1.0.0", optional = true}
python-lsp-server = {version = "^1.7.3", optional = true}


[tool.commitizen]
# See: https://commitizen-tools.github.io/commitizen/
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true  # TODO: change it when version >= 1.0.0
version_files = [
    "apc_lemmy_bot/__init__.py:^__version__",
    "pyproject.toml:^version",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
apc_lemmy_bot = "apc_lemmy_bot.__main__:main"

[tool.poetry.build]
generate-setup-file = false
script = "scripts/build.py"

[tool.black]
line-length = 89

[tool.pylint.messages_control]
max-line-length = 89
