[project]
# Used by cx_Freeze
name = "apc-lemmy-bot"
version = "0.2.0"
description = "Post supabase events to a Lemmy instance or show them."

[tool.poetry]
name = "apc-lemmy-bot"
version = "0.2.0"
description = "Post supabase events to a Lemmy instance or show them."
authors = ["Carles Muñoz Gorriz <carlesmu@internautas.org>"]
maintainers = ["Carles Muñoz Gorriz <carlesmu@internautas.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"
keywords = ["lemmy"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
]
packages = [
    {include = "apc_lemmy_bot"}
]
include = [
    "CHANGELOG.md",
    { path = "scripts", format = ["sdist"] },
]
exclude = []

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
typer = "^0.9.0"
typing-extensions = "^4.7.1"
supabase = "^1.0.3"
pythorhead = "^0.12.3"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
pylint = {extras = ["spelling"], version = "^2.17.4"}
pydocstyle = "^6.3.0"
pre-commit = "^3.3.3"
trove-classifiers = "^2023.7.6"  # for classifiers in this file
commitizen = "^3.5.2"
poetry = "^1.5.1"
prompt-toolkit = "^3.0.39"  # for comitizen 3.5.2
cx-freeze = "^6.15.3"
mypy = "^1.4.1"
sqlalchemy = {extras = ["mypy"], version = "^2.0.18"}
taskipy = "^1.11.0"

[tool.commitizen]
# See: https://commitizen-tools.github.io/commitizen/
name = "cz_conventional_commits"
tag_format = "v$version"
version_scheme = "pep440"
version_provider = "poetry"
update_changelog_on_bump = true
major_version_zero = true  # TODO: change it when version >= 1.0.0
version_files = [
    "apc_lemmy_bot/__init__.py:^__version__",
    "pyproject.toml:^version",
]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
apc_lemmy_bot = "apc_lemmy_bot.__main__:main"

[tool.poetry.build]
generate-setup-file = false
script = "scripts/build.py"

[tool.black]
line-length = 89

[tool.pylint.main]
recursive = true
suggestion-mode = true
exit-zero = true
load-plugins="pylint.extensions.docparams"

[tool.pylint.basic]
docstring-min-length = 5

[tool.pylint.design]

[tool.pylint.exceptions]

[tool.pylint.format]
max-line-length = 89

[tool.pylint.messages_control]

[tool.pylint.imports]

[tool.pylint.logging]
logging-format-style = "new"

[tool.pylint."messages control"]

[tool.pylint.method_args]

[tool.pylint.miscellaneous]

[tool.pylint.refactoring]

[tool.pylint.reports]
reports = true
score = true

[tool.pylint.similarities]

[tool.pylint.spelling]
spelling-dict = "en_US"
spelling-private-dict-file = "scripts/extended-dictionary.txt"
spelling-ignore-words = "bool, datetime"

[tool.pylint.typecheck]

[tool.pylint.variables]


[tool.mypy]
namespace_packages = false
show_error_context = true
show_column_numbers = true
pretty = true
error_summary = true
plugins = "sqlalchemy.ext.mypy.plugin"
warn_return_any = true
warn_redundant_casts = true
warn_unused_configs = true

[[tool.mypy.overrides]]
module = "cx_Freeze.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pythorhead.*"
ignore_missing_imports = true

[tool.taskipy.settings]
use_vars = true

[tool.taskipy.variables]
t_src = "*.py scripts/*.py apc_lemmy_bot"

[tool.taskipy.tasks]
# These tasks can be run with .venv/bin/poetry run task
lint = {cmd = "task lint-doc && task lint-src && task lint-mypy", help = "runs all lint-* tests"}
lint-src = {cmd = "pylint --enable-all-extensions {t_src}", help = "runs pylint"}
lint-doc = {cmd = "pydocstyle --convention=numpy {t_src}", help = "runs pydocstyle"}
lint-mypy = {cmd = "mypy {t_src}", help = "runs mypy"}
lintf-src = {cmd = "pylint --enable-all-extensions", help = "runs pylint in a file (argument)"}
lintf-doc = {cmd = "pydocstyle --convention=numpy", help = "runs pydocstyle in a file (argument)"}
lintf-mypy = {cmd = "mypy ", help = "runs mypy in a file (argument)"}
